(defun eval (exp env)
(cond
((atom exp) (assoc exp env))
((atom (car exp))
(cond ((eq ’quote (car exp)) (cadr exp))
((eq ’atom (car exp)) (atom (eval (cadr exp) env)))
((eq ’eq (car exp))
(eq (eval (cadr exp) env) (eval (caddr exp) env)))
((eq ’car (car exp)) (car (eval (cadr exp) env)))
((eq ’cdr (car exp)) (cdr (eval (cadr exp) env)))
((eq ’cons (car exp))
(cons (eval (cadr exp) env) (eval (caddr exp) env)))
((eq ’cond (car exp)) (condeval (cdr exp) env))
(’t (eval (cons (assoc (car exp) env) (cdr exp)) env))))
((eq (caar exp) ’label)
(eval (cons (caddar exp) (cdr exp))
(cons (list (cadar exp) (car exp)) env)))
((eq (caar exp) ’lambda)
(eval (caddar exp)
(append (pair (cadar exp) (listeval (cdr exp) env)) env)))
))
