name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test CoreLispTests/CoreLispTests.csproj --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack -c Release corelisp/CoreLisp.csproj
    - name: uploadNuget 
      uses: actions/upload-artifact@v1
      with:
        name: corelisp.nupkg
        path:   corelisp/bin/Release/Corelisp*.nupkg
