name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test CoreLispTests/CoreLispTests.csproj --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack -c Release 
    - name: Publish NuGet
      uses: rohith/publish-nuget@v2.3.0
      with:
        PROJECT_FILE_PATH: CoreLisp/CoreLisp.csproj
        VERSION_FILE_PATH: CoreLisp/version.txt
        NUGET_KEY: ${{secrets.NUGET_KEY}}
   
